export interface Property {
  id: string;
  name: string;
  subtitle: string;
  bedrooms: number;
  description: string;
  fullDescription: string;
  price: string;
  images: string[];
  thumbnail?: string;
  features: string[];
  amenities: string[];
  location: {
    lat: number;
    lng: number;
  };
  walkingDistance: string;
  videoUrl?: string;
  eircode?: string;
  /** Matterport (or compatible) showcase URL for 360° embed */
  matterportUrl?: string;
  /** When set (e.g. "5-6"), used in UI/SEO instead of `${bedrooms}` for bedroom count */
  bedroomsLabel?: string;
  /** Optional at-a-glance stats shown on property detail (label + value). */
  specs?: { label: string; value: string }[];
  /** Card badge; defaults to AVAILABLE when omitted. */
  availabilityStatus?: "AVAILABLE" | "RESERVED";
}

export function getPropertyAvailabilityLabel(
  property: Pick<Property, "availabilityStatus">,
): "AVAILABLE" | "RESERVED" {
  return property.availabilityStatus ?? "AVAILABLE";
}

export function formatPropertyBedroomsShort(property: Pick<Property, "bedrooms" | "bedroomsLabel">): string {
  return property.bedroomsLabel ?? String(property.bedrooms);
}

/** Uppercase label on property cards and gallery (homepage, listing, detail). */
export function getPropertyCollectionBadge(propertyId: string): string {
  if (propertyId === "croagh-house") return "PREMIUM";
  if (["darrira-house", "dunes-lodge", "parkview-house", "oak-leaf-house"].includes(propertyId)) return "DELUXE";
  return "EXECUTIVE";
}

const COLLECTION_TIER_ORDER: Record<string, number> = {
  EXECUTIVE: 0,
  PREMIUM: 1,
  DELUXE: 2,
};

/**
 * Property IDs temporarily hidden from the homepage and /properties listings.
 * The property detail page (/property/<id>) and direct links still work.
 * To re-list a property, remove its id from this array.
 */
export const HIDDEN_FROM_LISTINGS: string[] = [];

/** Listing feed for homepage + /properties, excluding temporarily hidden properties. */
export function getListedProperties(): Property[] {
  return properties.filter((p) => !HIDDEN_FROM_LISTINGS.includes(p.id));
}

/** Homepage / listing order: Executive → Premium → Deluxe, preserving source order within each tier. */
export function sortPropertiesByCollectionTier(list: readonly Property[]): Property[] {
  const indexById = new Map(properties.map((p, i) => [p.id, i]));
  return [...list].sort((a, b) => {
    const tierDiff =
      (COLLECTION_TIER_ORDER[getPropertyCollectionBadge(a.id)] ?? 0) -
      (COLLECTION_TIER_ORDER[getPropertyCollectionBadge(b.id)] ?? 0);
    if (tierDiff !== 0) return tierDiff;
    return (indexById.get(a.id) ?? 0) - (indexById.get(b.id) ?? 0);
  });
}

export const properties: Property[] = [
  {
    id: "rangeview",
    name: "Range View",
    subtitle: "Located within Adare Manor estate, offering front-row proximity to Ryder Cup 2027",
    bedrooms: 6,
    bedroomsLabel: "5/6",
    description: "Located within Adare Manor estate, offering front-row proximity to Ryder Cup 2027.",
    fullDescription: "Range View is a luxurious residence nestled within the private and gated enclave of The Demesne, just 300 yards from the Ryder Cup 2027 driving range and a five-minute walk to the first tee box. Offering over 7,000ft²/650m² of living space across three expansive floors, this home delivers unrivalled proximity to the Ryder Cup.",
    specs: [
      { label: "Bedrooms", value: "5/6 double rooms ensuite" },
      { label: "Bathrooms", value: "5 + 2 half bathrooms" },
      { label: "Occupancy", value: "12 max." },
      { label: "Distance from Adare Manor course", value: "300 yards." },
      { label: "Number of TVs", value: "5" },
      { label: "Square footage", value: "7,000 sqft" },
      { label: "Dining seating", value: "18" },
      { label: "Kitchen seating", value: "12" },
    ],
    price: "Enquire Now",
    images: [
      "/images/houses/house 2/house-2-main-original.webp",
      "/images/houses/house 2/house-2-stairway-1.webp",
      "/images/houses/house 2/house-2-living-room-3.webp",
      "/images/houses/house 2/house-2-living-room-2.webp",
      "/images/houses/house 2/house-2-living-room-1.webp",
      "/images/houses/house 2/house-2-living-room-4.webp",
      "/images/houses/house 2/house-2-living-room.webp",
      "/images/houses/house 2/house-2-dining.webp",
      "/images/houses/house 2/house-2-cinema-room.webp",
      "/images/houses/house 2/house-2-master-bedroom.webp",
      "/images/houses/house 2/house-2-master-bedroom-2.webp",
      "/images/houses/house 2/house-2-master-changing-room.webp",
      "/images/houses/house 2/house-2-master-bathroom.webp",
      "/images/houses/house 2/house-2-bedroom-2.webp",
      "/images/houses/house 2/house-2-bedroom-1.webp",
      "/images/houses/house 2/house-2-bathroom-1.webp",
      "/images/houses/house 2/house-2-bathroom-2.webp",
      "/images/houses/house 2/house-2-bathroom-3.webp",
      "/images/houses/house 2/house-2-games-room.webp",
      "/images/houses/house 2/house-2-study.webp",
      "/images/houses/house 2/house-2-sauna.webp",
      "/images/houses/house 2/house-2-gym.webp",
      "/images/houses/house 2/house-2-outdoor-seating.webp"
    ],
    thumbnail: "/images/houses/house 2/house-2-main-original.webp",
    features: [
      "Fully equipped lounge bar with draught taps, keg room, pool table and classic 'Pac-man' arcade game.",
      "Grand chandelier-lit entrance hall with open fireplace",
      "6 double ensuite bedrooms including a 95m² master suite with jacuzzi bath",
      "Formal sitting room flowing into a dining room for up to 18 guests",
      "Expansive gourmet kitchen with walk-in cold room and professional-grade appliances",
      "Large outdoor areas including 3230ft²/300m² of landscaped gardens and 2690ft²/250m² of Liscannor paving, perfect for marquee events (up to 100 guests)",
    ],
    amenities: [
      "Private cinema room with retractable projector, stereo system, and automatic blinds",
      "Fitness suite including gym, sauna, and shower facilities",
      "Executive home office",
      "High-speed WiFi and satellite TV",
      "Daily housekeeping",
      "BBQ and smoker",
      "Secure private parking",
    ],
    location: {
      lat: 52.55891014565409,
      lng: -8.78703798127682
    },
    walkingDistance: "Just a short stroll to Ryder Cup practice range and golf course",
    videoUrl: "/videos/rangeview.mp4"
  },
  {
    id: "the-captains",
    name: "The Captains",
    subtitle: "Within Adare Manor's secure walls, 'Captains House' places you close to the championship course in complete privacy.",
    bedrooms: 6,
    bedroomsLabel: "6",
    description: "Within Adare Manor grounds, close to the championship course in complete privacy.",
    fullDescription: "Situated within the exclusive walls of the Adare Manor grounds, this home offers an extraordinary opportunity to stay at the epicentre of the Ryder Cup 2027. This six-bedroom estate spanning over 8500ft²/790m² is not just near the event. It is almost part of it.\n\nWith the practice range just minutes' walk away and a 5 minute stroll from the 1st tee box, this residence is ideal for guests seeking to be immersed in the Ryder Cup action, without compromising on space, luxury, or privacy.",
    specs: [
      { label: "Bedrooms", value: "6 double rooms ensuite" },
      { label: "Bathrooms", value: "6 + 2 half bathrooms" },
      { label: "Occupancy", value: "12 max." },
      { label: "Distance from Adare Manor course", value: "300 yards." },
      { label: "Number of TVs", value: "4" },
      { label: "Square footage", value: "8,500 sqft" },
      { label: "Dining seating", value: "10 plus" },
      { label: "Kitchen seating", value: "10" },
    ],
    price: "POA",
    images: [
      "/images/houses/house 3/house-3-main-original.webp",
      "/images/houses/house 3/house-3-entry-hall.webp",
      "/images/houses/house 3/house-3-kitchen.webp",
      "/images/houses/house 3/house-3-kitchen-2.webp",
      "/images/houses/house 3/house-3-kitchen-3.webp",
      "/images/houses/house 3/house-3-living-room-1.webp",
      "/images/houses/house 3/house-3-living-room-2.webp",
      "/images/houses/house 3/house-3-living-room-3.webp",
      "/images/houses/house 3/house-3-living-room-4.webp",
      "/images/houses/house 3/house-3-living-room-5.webp",
      "/images/houses/house 3/house-3-living-room-6.webp",
      "/images/houses/house 3/house-3-living-room-7.webp",
      "/images/houses/house 3/house-3-stairs.webp",
      "/images/houses/house 3/house-3-chandelier.webp",
      "/images/houses/house 3/house-3-reading-room.webp",
      "/images/houses/house 3/house-3-bedroom-1.webp",
      "/images/houses/house 3/house-3-bedroom-2.webp",
      "/images/houses/house 3/house-3-bedroom-3.webp",
      "/images/houses/house 3/house-3-master-bath-1.webp",
      "/images/houses/house 3/house-3-master-bath-2.webp",
      "/images/houses/house 3/house-3-master-bath-3.webp",
      "/images/houses/house 3/house-3-bedroom-4.webp",
      "/images/houses/house 3/house-3-bedroom-6.webp",
      "/images/houses/house 3/house-3-bedroom-7.webp",
      "/images/houses/house 3/house-3-bedroom-9.webp",
      "/images/houses/house 3/house-3-bedroom-11.webp",
      "/images/houses/house 3/house-3-exterior.webp"
    ],
    thumbnail: "/images/houses/house 3/house-3-main-original.webp",
    features: [
      "Six luxury ensuite bedrooms, including an exquisite master suite with jacuzzi bath, open fireplace, and walk-in wardrobe",
      "Grand entrance hall with crystal chandelier and a grand piano, perfect for welcoming guests or evening entertainment.",
      "Three elegant reception areas: a large drawing room and two sitting rooms with ample tranquil seating",
      "Open-plan kitchen and living space with high-end finishes, adjoining a formal dining room for 10 people",
      "Separate dining area capable of hosting 50+ guests.",
    ],
    amenities: [
      "Daily housekeeping",
      "High-speed Wi-Fi and satellite TV",
      "Games room with pool table, table tennis, and dart board; convertible into a fitness studio with treadmill (if required)",
      "Secure private parking",
    ],
    location: {
      lat: 52.55909971573407,
      lng: -8.786145768660083
    },
    walkingDistance: "Just a short stroll to Ryder Cup practice range and golf course",
    videoUrl: "/videos/thecaptains.mp4"
  },
  {
    id: "putters-way",
    name: "Putters Way",
    subtitle: "At the very centre of Ryder Cup 2027, Golf Village, Adare Manor",
    bedrooms: 2,
    bedroomsLabel: "2",
    description: "At the very centre of Ryder Cup 2027, metres from the range and a one-minute stroll to the 1st tee.",
    fullDescription: "Putters Way is a rare and exclusive opportunity to stay close to the championship course 2027. Situated just metres from where the U.S and European team will warm up on the practice range and putting green and a one minute stroll to the 1st tee, it just doesn't get any closer than this!\n\nLocated in the prestigious private Golf Village, this property places guests at the centre of the tournament atmosphere.",
    specs: [
      { label: "Bedrooms", value: "2 double rooms ensuite" },
      { label: "Bathrooms", value: "2 bathrooms" },
      { label: "Occupancy", value: "8 max." },
      { label: "Distance from Adare Manor course", value: "100 yards." },
      { label: "Number of TVs", value: "1" },
      { label: "Square footage", value: "1300 sqft" },
      { label: "Kitchen/Dining seating", value: "4-6" },
    ],
    price: "POA",
    images: [
      "/images/houses/house 4/adare-house-4-original.webp",
      "/images/houses/house 4/house-4-dining.webp",
      "/images/houses/house 4/house-4-dining-2.webp",
      "/images/houses/house 4/house-4-living.webp",
      "/images/houses/house 4/house-4-living-2.webp",
      "/images/houses/house 4/house-4-bedroom.webp",
      "/images/houses/house 4/house-4-bathroom.webp",
      "/images/houses/house 4/house-4-exterior.webp",
      "/images/houses/house 4/house-4-rolex.webp"
    ],
    thumbnail: "/images/houses/house 4/adare-house-4-original.webp",
    features: [
      "Modern, bright open-plan kitchen and dining room, perfect for entertaining or relaxing after a day on the course",
      "Spacious, beautifully appointed sitting room with premium seating and contemporary comforts",
      "Tastefully designed interiors that combine modern luxury with Irish elegance",
      "Two double ensuite bedrooms, each with two double beds, ideal for small groups or executive stays"
    ],
    amenities: [
      "Located at the centre of the Adare Manor resort",
      "High-speed internet access",
      "Premium seating and entertainment areas",
      "Daily housekeeping"
    ],
    location: {
      lat: 52.56182292270544,
      lng: -8.780515540696719
    },
    walkingDistance: "1 minute stroll to the 1st tee box",
    videoUrl: "/videos/puttersway.mp4"
  },
  {
    id: "the-first-tee",
    name: "The First Tee",
    subtitle: "Closest Demesne residence to the Ryder Cup course, just 150 yards from the practice range and 1st tee.",
    bedrooms: 5,
    bedroomsLabel: "5/6",
    description: "Closest Demesne residence to the Ryder Cup course, just 150 yards from the practice range and 1st tee.",
    fullDescription: "Nestled within the prestigious grounds of Adare Manor, just steps from the world-renowned championship course and practice facilities, The First Tee offers a truly unrivalled location during tournament week.\n\nPositioned closer to the championship course than any other residence in The Demesne, this exceptional home provides a rare opportunity to stay quite literally at the starting point of one of the world's most celebrated golfing experiences.\n\nDesigned with elegance and comfort in mind, the property blends timeless architecture with refined contemporary interiors. Expansive living spaces filled with natural light create a seamless flow throughout, offering both relaxed and formal settings for entertaining, unwinding, or hosting in style.\n\nThe residence features 5-6 beautifully appointed bedrooms, including four en-suite, alongside luxurious bathrooms designed for comfort and relaxation after a day on the course.",
    specs: [
      { label: "Bedrooms", value: "5/6 double rooms, 4 ensuite" },
      { label: "Bathrooms", value: "5 + 1 half bathroom" },
      { label: "Occupancy", value: "12 max." },
      { label: "Distance from Adare Manor course", value: "150 yards." },
      { label: "Number of TVs", value: "3" },
      { label: "Square footage", value: "5,000 sqft" },
      { label: "Dining seating", value: "8-12" },
      { label: "Kitchen seating", value: "5 plus" },
    ],
    price: "POA",
    images: [
      "/images/houses/house 7/house-7-exterior-3.webp",
      "/images/houses/house 7/house-7-hallway-1.webp",
      "/images/houses/house 7/house-7-hallway-2.webp",
      "/images/houses/house 7/house-7-kitchen-1.webp",
      "/images/houses/house 7/house-7-kitchen-2.webp",
      "/images/houses/house 7/house-7-dining-1.webp",
      "/images/houses/house 7/house-7-lounge-1.webp",
      "/images/houses/house 7/house-7-sitting-room-1.webp",
      "/images/houses/house 7/house-7-downstairs-bathroom-1.webp",
      "/images/houses/house 7/house-7-master-bedroom-1.webp",
      "/images/houses/house 7/house-7-master-bathroom-1.webp",
      "/images/houses/house 7/house-7-master-bathroom-2.webp",
      "/images/houses/house 7/house-7-second-bedroom-1.webp",
      "/images/houses/house 7/house-7-fourth-bedroom-2.webp",
      "/images/houses/house 7/house-7-fourth-bedroom-1.webp",
      "/images/houses/house 7/house-7-fourth-bedroombath-1.webp",
      "/images/houses/house 7/house-7-fourth-bedroombath-2.webp",
      "/images/houses/house 7/house-7-fourth-bedroombath-3.webp",
      "/images/houses/house 7/house-7-second-bedroom-2.webp",
      "/images/houses/house 7/house-7-third-bedroom-1.webp",
      "/images/houses/house 7/house-7-third-bedroom-2.webp",
      "/images/houses/house 7/house-7-fifth-bedroom-1.webp",
      "/images/houses/house 7/house-7-snooker-1.webp",
      "/images/houses/house 7/house-7-exterior-1.webp"
    ],
    thumbnail: "/images/houses/house 7/house-7-exterior-3.webp",
    features: [
      "Located on the grounds of Adare Manor",
      "Multiple reception rooms and lounges",
      "Open-plan kitchen and dining areas",
      "Formal dining room",
      "Pool room",
      "Luxury bathroom with jacuzzi bath",
      "High-quality finishes throughout",
      "Private driveway with parking",
      "Landscaped grounds",
    ],
    amenities: [
      "Fully equipped kitchen",
      "High-speed Wi-Fi",
      "Multiple living areas",
      "Luxury bathrooms with jacuzzi bath and walk-in showers",
      "Large outdoor patio for evening BBQs",
      "Home office space",
      "Laundry facilities",
      "Quality bed linen and towels provided",
      "Secure private setting"
    ],
    location: {
      lat: 52.56157892845145,
      lng: -8.787714781150669
    },
    walkingDistance: "100 yards to Ryder Cup practice range",
    videoUrl: "/videos/thefirsttee.mp4",
    eircode: "V94 D40K"
  },
  {
    id: "the-fairways",
    name: "The Fairways",
    subtitle: "Located within the gates of Adare Manor, just steps from the 2027 Ryder Cup venue.",
    bedrooms: 6,
    bedroomsLabel: "6",
    description: "Within the gates of Adare Manor, just steps from the 2027 Ryder Cup venue.",
    fullDescription: "The Fairways is a contemporary luxury residence located within the Demesne, a luxury neighbourhood on the grounds of Adare Manor, offering unrivalled proximity to Ryder Cup 2027. This expansive 6-bedroom home spans over 3 floors of immaculately designed interiors, combining privacy, grandeur, and modern elegance.\n\nPositioned just a short walk from the 1st tee, this is one of the closest private properties at the heart of the tournament.",
    specs: [
      { label: "Bedrooms", value: "4 bed ensuite, 2 beds with shared bathroom" },
      { label: "Bathrooms", value: "6 + 1 half bathroom" },
      { label: "Occupancy", value: "12 max." },
      { label: "Distance from Adare Manor course", value: "200 yards." },
      { label: "Number of TVs", value: "4" },
      { label: "Square footage", value: "4,840 sqft" },
      { label: "Dining seating", value: "8" },
      { label: "Kitchen seating", value: "6" },
    ],
    price: "POA",
    images: [
      "/images/houses/house 1/house-1-main.webp",
      "/images/houses/house 1/house-1-hall.webp",
      "/images/houses/house 1/house-1-kitchen.webp",
      "/images/houses/house 1/house-1-kitchen-2.webp",
      "/images/houses/house 1/house-1-living-room.webp",
      "/images/houses/house 1/house-1-living-room-2.webp",
      "/images/houses/house 1/house-1-living-room-3.webp",
      "/images/houses/house 1/house-1-living-room-4.webp",
      "/images/houses/house 1/house-1-bedroom-1.webp",
      "/images/houses/house 1/house-1-bedroom-2.webp",
      "/images/houses/house 1/house-1-bedroom-3.webp",
      "/images/houses/house 1/house-1-bedroom-4.webp",
      "/images/houses/house 1/house-1-bedroom-5.webp",
      "/images/houses/house 1/house-1-bedroom-6.webp",
      "/images/houses/house 1/house-1-gym.webp",
      "/images/houses/house 1/house-1-exterior-3.webp",
      "/images/houses/house 1/house-1-exterior-4.webp",
      "/images/houses/house 1/house-1-exterior-1.webp",
      "/images/houses/house 1/house-1-exterior-2.webp"
    ],
    thumbnail: "/images/houses/house 1/house-1-main-optimized.webp",
    features: [
      "Grand entrance foyer with natural light and architectural presence",
      "Exquisite master suite (860ft²/80m²) with lounge, dual walk-in wardrobes, jacuzzi bath, double vanity, and dual showers",
      "Five additional double bedrooms",
      "Two spacious formal lounges with TV and large seating areas",
      "Upper-level private retreat with lounge/TV space, shower, bath, and a fully fitted office",
      "Large open-plan kitchen with premium appliances, dual ovens, gas stove, under-counter fridges, and a full utility room",
      "Elegant dining area adjoining a conservatory that opens to the garden"
    ],
    amenities: [
      "Fitness Suite: a fully equipped private gym above the garage",
      "Firepit Terrace & Gazebo: covered outdoor living area with built-in fireplace, lounge seating for 10 to 12, and Kamado Joe BBQ",
      "Secluded rear garden with patio, dining area, and cushioned seating for al fresco entertaining",
      "High-speed WiFi & Satellite TV",
      "Daily housekeeping",
      "Secure private parking",
    ],
    location: {
      lat: 52.561116990572174,
      lng: -8.788021971381418
    },
    walkingDistance: "Just a short stroll to Ryder Cup practice range and golf course",
    videoUrl: "/videos/thefairways.mp4"
  },
  {
    id: "cragleigh-house",
    name: "Cragleigh House",
    subtitle: "Located just 15 drive minutes from Adare Manor with convenient access to Limerick, the M20 motorway, and Shannon Airport. Cragleigh House offers privacy, space, and effortless access to Ryder Cup 2027",
    bedrooms: 5,
    bedroomsLabel: "5",
    description: "Just 15 minutes from Adare Manor, manor-style estate with space and effortless Ryder Cup access.",
    fullDescription: "Cragleigh House is a magnificent manor-style residence located just under 15 minutes drive from the Ryder Cup 2027 venue at Adare Manor. Positioned within easy reach of the action, this elegant estate combines traditional charm with modern luxury across extensive gardens and refined interiors.\n\nOffering five spacious double bedrooms, multiple reception rooms, and formal dining areas, Cragleigh House is ideal for groups or families.",
    specs: [
      { label: "Bedrooms", value: "5 double rooms; 1 master ensuite, 2 x 2 Jack and Jill." },
      { label: "Bathrooms", value: "4" },
      { label: "Occupancy", value: "10-12 max." },
      { label: "Distance from Adare Manor course", value: "11 miles (15 mins drive)" },
      { label: "Distance to Park and Ride", value: "4.7mls (10 minutes drive)" },
      { label: "Number of TVs", value: "4" },
      { label: "Square footage", value: "5,500 sq ft" },
      { label: "Dining seating", value: "8" },
      { label: "Kitchen seating", value: "6" },
    ],
    price: "POA",
    images: [
      "/images/houses/house 5/cragleighhouse-main.webp",
      "/images/houses/house 5/cragleigh-interior.webp",
      "/images/houses/house 5/cragleigh-dining.webp",
      "/images/houses/house 5/cragleigh-house-living-room-2.webp",
      "/images/houses/house 5/cragleigh-house-living-room-1.webp",
      "/images/houses/house 5/cragleigh-master-bedroom.webp",
      "/images/houses/house 5/cragleigh-master-ensuite.webp",
      "/images/houses/house 5/cragleigh-master-ensuite-2.webp",
      "/images/houses/house 5/cragleigh-bedroom-1.webp",
      "/images/houses/house 5/cragleigh-bedroom-2.webp",
      "/images/houses/house 5/cragleigh-bedroom-3.webp",
      "/images/houses/house 5/cragleigh-patio.webp"
    ],
    thumbnail: "/images/houses/house 5/cragleighhouse-main.webp",
    features: [
      "Two large elegant sitting rooms with ample space for entertaining",
      "Two formal dining rooms suitable for private dining or group hosting",
      "Large kitchen ideal for pre-dinner drinks",
      "Extensive garden space suitable for outdoor receptions and large gatherings",
    ],
    amenities: [
      "Private gated and secure manor residence",
      "Beautifully landscaped outdoor areas",
      "Flexible living and dining spaces for formal or relaxed hosting",
      "Proximity to Limerick City, the M20 motorway, and Shannon Airport",
      "Daily housekeeping"
    ],
    location: {
      lat: 52.60043120307769,
      lng: -8.633705271352245
    },
    walkingDistance: "15 minutes drive",
    videoUrl: "/videos/cragleighhouse.mp4",
    availabilityStatus: "RESERVED",
  },
  {
    id: "darrira-house",
    name: "Darrira House",
    subtitle: "Just ten minutes from Adare Manor, an elegant private retreat in Croagh, County Limerick.",
    bedrooms: 5,
    bedroomsLabel: "5",
    description: "Just ten minutes from Adare Manor, an elegant private retreat in Croagh, County Limerick.",
    fullDescription: "Located just 12 minutes drive from Adare Manor, Darrira House offers an elegant retreat in the peaceful countryside of Croagh, County Limerick. With its beautifully furnished interiors and expansive outdoor spaces, this residence is ideally suited for guests seeking comfort and convenience.\n\nThe property has five bedrooms: a master ensuite; one double with shower and separate half bathroom; two doubles sharing the main bathroom; and a single guest bedroom, with one adapted to accommodate guests with specific accessibility needs. In total, the home offers two bathrooms, a wetroom and two half bathrooms.\n\nRamp access through the front door. Double doors from the hallway open into the sitting room, which flows into a spacious open-plan kitchen and onwards to a bright conservatory.",
    specs: [
      { label: "Bedrooms", value: "4 double bedrooms and 1 single bedroom" },
      { label: "Bathrooms", value: "2 bathrooms, wetroom and 2 half bathrooms" },
      { label: "Accessibility", value: "Downstairs double bedroom, adapted for special needs" },
      { label: "Kitchen & dining", value: "Stylish kitchen-dining space opening to conservatory" },
      { label: "Interiors", value: "Elegant interiors and abundant natural light" },
      { label: "Location", value: "Quiet village location just 10 minutes from Adare Manor" },
    ],
    price: "POA",
    images: [
      "/images/houses/house 6/house-6-exterior-1.webp",
      "/images/houses/house 6/house-6-kitchen-2.webp",
      "/images/houses/house 6/house-6-kitchen-1.webp",
      "/images/houses/house 6/house-6-kitchen-3.webp",
      "/images/houses/house 6/house-6-sunroom.webp",
      "/images/houses/house 6/house-6-livingroom.webp",
      "/images/houses/house 6/house-6-hallway.webp",
      "/images/houses/house 6/house-6-master-bedroom-2.webp",
      "/images/houses/house 6/house-6-master-bedroom-1.webp",
      "/images/houses/house 6/house-6-master-ensuite-1.webp",
      "/images/houses/house 6/house-6-master-ensuite-2.webp",
      "/images/houses/house 6/house-6-bedroom-2.webp",
      "/images/houses/house 6/house-6-bedroom-3.webp",
      "/images/houses/house 6/house-6-main-bathroom-1.webp",
      "/images/houses/house 6/house-6-jacuzzi.webp",
      "/images/houses/house 6/house-6-shower-room.webp"
    ],
    thumbnail: "/images/houses/house 6/house-6-exterior-1.webp",
    features: [
      "Master ensuite; 1 double with shower and separate half bathroom; 2 doubles sharing main bathroom",
      "2 bathrooms, wetroom and 2 half bathrooms",
      "Ramp access through the front door",
      "Sitting room flows into spacious open-plan kitchen and bright conservatory",
    ],
    amenities: [
      "Daily housekeeping",
      "High-speed WiFi",
      "Satellite TV",
      "Secure private parking"
    ],
    location: {
      lat: 52.551248755996916,
      lng: -8.874792660717345
    },
    walkingDistance: "10 minutes drive",
    videoUrl: "/videos/darrirahouse.mp4"
  },
  {
    id: "croagh-house",
    name: "Croagh House",
    subtitle: "Privacy and direct Ryder Cup access (12 minutes from Adare Manor, 3 minutes from the official Park & Ride).",
    bedrooms: 4,
    bedroomsLabel: "4/5",
    description:
      "Privacy and direct Ryder Cup access (12 minutes from Adare Manor, 3 minutes from the official Park & Ride).",
    fullDescription:
      "Croagh House offers a perfect base just 12 minutes drive from Adare Manor and 3 minutes drive from the official park & ride at Smithfield, ensuring direct access to the Ryder Cup. It is a private, modern residence curated for hosting and seamless access to the Ryder Cup.\n\nIts proximity to Parkview House also creates an opportunity for larger groups to secure adjacent accommodation, combining capacity with convenience.\n\nThe residence comprises 4-5 bedrooms (two en-suite), with the flexibility to accommodate an additional guest room on the ground floor if required. The master suite features a walk-in wardrobe and a spa-quality bathroom with a freestanding jacuzzi bath, walk-in shower, and double vanity.\n\nA grand entrance hallway with statement chandelier leads into multiple reception spaces, including a main living area with reclining seating and a separate media lounge, allowing for both formal hosting and relaxed downtime. The open-plan kitchen and dining area is designed for entertaining, featuring a bespoke in-frame kitchen finished with premium appliances including a Rangemaster cooker, smart American-style fridge/freezer, quartz worktops, and a wine fridge, with access to a private patio and garden.",
    specs: [
      { label: "Bedrooms", value: "4/5 double rooms; 2 ensuite, 2 with shared bathroom." },
      { label: "Bathrooms", value: "4" },
      { label: "Occupancy", value: "8-10 max." },
      { label: "Distance from Adare Manor course", value: "6 miles (12 mins drive)" },
      { label: "Distance to Park and Ride", value: "1.8mls (3 minutes drive)" },
      { label: "Number of TVs", value: "3" },
      { label: "Square footage", value: "2,500 sq ft" },
      { label: "Dining seating", value: "6-8" },
      { label: "Kitchen seating", value: "3" },
    ],
    price: "POA",
    images: [
      "/images/houses/croaghhouse/exterior/croaghhouse-exterior-2.webp",
      "/images/houses/croaghhouse/kitchen/croaghhouse-kitchen-2.webp",
      "/images/houses/croaghhouse/kitchen/croaghhouse-kitchen-1.webp",
      "/images/houses/croaghhouse/sittingroom/croaghhouse-sittingroom-1.webp",
      "/images/houses/croaghhouse/sittingroom/croaghhouse-sittingroom-2.webp",
      "/images/houses/croaghhouse/stairs/croaghhouse-stairs-1.webp",
      "/images/houses/croaghhouse/landing/croaghhouse-landing-1.webp",
      "/images/houses/croaghhouse/masterbedroom/croaghhouse-masterbedroom-1.webp",
      "/images/houses/croaghhouse/masterbedroom/croaghhouse-masterbedroom-2.webp",
      "/images/houses/croaghhouse/masterbedroom/croaghhouse-masterbedroom-closet-1.webp",
      "/images/houses/croaghhouse/masterbedroom/croaghhouse-masterbedroom-bathroom-2.webp",
      "/images/houses/croaghhouse/masterbedroom/croaghhouse-masterbedroom-bathroom-1.webp",
      "/images/houses/croaghhouse/masterbedroom/croaghhouse-masterbedroom-bathroom-3.webp",
      "/images/houses/croaghhouse/bedroom 2/croaghhouse-bedroom2-1.webp",
      "/images/houses/croaghhouse/bedroom 2/croaghhouse-bedroom2-2.webp",
      "/images/houses/croaghhouse/bedroom 3/croaghhouse-bedroom3.webp",
      "/images/houses/croaghhouse/bedroom 4/croaghhouse-bedroom4.webp",
      "/images/houses/croaghhouse/exterior/croaghhouse-exterior-1.webp",
      "/images/houses/croaghhouse/bathroom/croaghhouse-bathroom-1.webp",
      "/images/houses/croaghhouse/utilitiyroom/croaghhouse-utilitybathroom-1.webp",
      "/images/houses/croaghhouse/utilitiyroom/croaghhouse-utilitybathroom-2.webp",
      "/images/houses/croaghhouse/utilitiyroom/croaghhouse-utilitybathroom-3.webp"
    ],
    thumbnail: "/images/houses/croaghhouse/exterior/croaghhouse-exterior-2.webp",
    features: [
      "4-5 bedrooms; 2 en-suite bedrooms",
      "Additional ground floor bedroom option",
      "Master suite with walk-in wardrobe; spa-style bathroom with jacuzzi, walk-in shower, and double vanity",
      "Large main bathroom and shower",
      "Ground-floor bathroom with shower",
      "Secure gated property with private driveway",
      "12 minutes to Adare Manor; 3 minutes to official Park & Ride (Smithfield)",
      "Separate media / lounge room",
    ],
    amenities: [
      "High-speed Wi-Fi throughout",
      "Smart TVs and entertainment systems",
      "Fully equipped modern kitchen",
      "Dedicated laundry facilities",
      "Quality bed linen and towels provided",
      "Multiple contemporary bathrooms",
      "Ample private parking within secure grounds",
      "Outdoor dining and seating areas",
      "Climate-controlled interior",
      "Available on request: private chauffeur and executive transport; in-residence chef and bespoke dining; daily housekeeping and laundry; tailored hospitality and entertainment",
    ],
    location: {
      lat: 52.54885726209432,
      lng: -8.880012509768715
    },
    walkingDistance: "Approximately 12 minutes' drive to Adare Manor; about 3 minutes to the Croagh Park & Ride at Smithfield.",
    matterportUrl: "https://my.matterport.com/show/?m=geo8qL777Pz"
  },
  {
    id: "parkview-house",
    name: "Parkview House",
    subtitle:
      "High-capacity private residence for up to 12 guests (12 minutes from Adare Manor, 3 minutes from the official Park & Ride).",
    bedrooms: 6,
    bedroomsLabel: "6/7",
    description:
      "High-capacity private residence for up to 12 guests (12 minutes from Adare Manor, 3 minutes from the official Park & Ride).",
    fullDescription:
      "Parkview House is a private residence positioned just 12 minutes drive from Adare Manor and only 3 minutes drive from the official Park & Ride at Smithfield, offering one of the most practical and accessible bases available for Ryder Cup 2027.\n\nLocated within a quiet, residential setting, the property is ideally configured for group hosting at scale, accommodating up to 12 guests across a flexible 6-7 bedroom layout. Its proximity to Croagh House also creates a rare opportunity for larger groups to secure adjacent accommodation, combining capacity with convenience.\n\nInside, the home is designed around comfort and flow, with multiple living spaces that allow guests to host, or unwind with ease. A bright, open-plan kitchen and dining area, complemented by a sunroom and two separate reception rooms, each with its own open fireplace.\n\nThe bedroom configuration is well suited to group stays, offering a mix of ensuite and shared arrangements that maximise both privacy and capacity. The master bedroom includes an ensuite bathroom, while a second ensuite bedroom and additional shared bathrooms support the remaining rooms. A Jacuzzi bath in the main bathroom provides a welcome space to relax after a day on the course.",
    specs: [
      { label: "Bedrooms", value: "6/7 bedrooms; 2 doubles ensuite, 1 double and one twin with shared bathroom. One triple and a single room with shared bathroom." },
      { label: "Bathrooms", value: "4" },
      { label: "Occupancy", value: "12" },
      { label: "Distance from Adare Manor course", value: "6 miles (12 mins drive)" },
      { label: "Distance to Park and Ride", value: "1.8mls (3 minutes drive)" },
      { label: "Number of TVs", value: "3" },
      { label: "Square footage", value: "2,500 sq ft" },
      { label: "Dining seating", value: "8-10" },
      { label: "Kitchen seating", value: "4" },
    ],
    price: "POA",
    images: [
      "/images/houses/parkviewhouse/exterior/parkview-exterior-1.webp",
      "/images/houses/parkviewhouse/kitchen/parkview-kitchen-1.webp",
      "/images/houses/parkviewhouse/kitchen/parkview-kitchen-2.webp",
      "/images/houses/parkviewhouse/conservatory/parkview-conservatory-1.webp",
      "/images/houses/parkviewhouse/sitting-room/parkview-sitting-room-1.webp",
      "/images/houses/parkviewhouse/sitting-room/parkview-sitting-room-2.webp",
      "/images/houses/parkviewhouse/landing/parkview-landing-1.webp",
      "/images/houses/parkviewhouse/master-bedroom/parkview-master-bedroom-1.webp",
      "/images/houses/parkviewhouse/master-bedroom/parkview-master-bedroom-2.webp",
      "/images/houses/parkviewhouse/master-bedroom/parkview-master-bedroom-3.webp",
      "/images/houses/parkviewhouse/bedroom 2/parkview-bedroom2-1.webp",
      "/images/houses/parkviewhouse/bedroom 2/parkview-bedroom2-2.webp",
      "/images/houses/parkviewhouse/bedroom 2/parkview-bedroom2-3.webp",
      "/images/houses/parkviewhouse/bedroom 3/parkview-bedroom3-1.webp",
      "/images/houses/parkviewhouse/bedroom 4/parkview-bedroom4-1.webp",
      "/images/houses/parkviewhouse/bedroom 5/parkview-bedroom5-1.webp",
      "/images/houses/parkviewhouse/bedroom 5/parkview-bedroom6-1.webp",
      "/images/houses/parkviewhouse/utility-room/parkview-utility-room-1.webp"
    ],
    thumbnail: "/images/houses/parkviewhouse/exterior/parkview-exterior-1.webp",
    features: [
      "Accommodates up to 12 guests",
      "6-7 bedroom configuration",
      "Master ensuite bedroom, 2 doubles, one twin, triple and a single room",
      "Main bathroom with Jacuzzi bath",
      "Two reception rooms with open fireplaces",
      "Bright sunroom",
      "Large open-plan kitchen and dining area",
      "Private driveway with ample parking",
    ],
    amenities: [
      "Fully equipped kitchen",
      "High-speed Wi-Fi throughout",
      "Smart TVs and entertainment systems",
      "Dedicated laundry facilities",
      "Quality bed linen and towels provided",
      "Multiple bathrooms",
      "Ample private parking within secure grounds",
    ],
    location: {
      lat: 52.54854779330623,
      lng: -8.880395148400085
    },
    walkingDistance: "Approximately 12 minutes' drive to Adare Manor; about 3 minutes to the Croagh Park & Ride at Smithfield.",
    eircode: "V94 K3EX",
    matterportUrl: "https://my.matterport.com/show/?m=BxbEQdSmPXo",
    availabilityStatus: "RESERVED",
  },
  {
    id: "dunes-lodge",
    name: "Dunes Lodge",
    subtitle: "Architect-designed A-rated home in Lahinch with sea and golf course views, ideal for Ryder Cup 2027 stays.",
    bedrooms: 4,
    description: "Architect-designed A-rated home overlooking the Lahinch Old Course along the Wild Atlantic Way.",
    fullDescription: "Located in the vibrant surf and golf town of Lahinch along the scenic Wild Atlantic Way, Dunes Lodge is a recently renovated, architect-designed A-rated energy-efficient home. It provides an idyllic retreat for golfers, surfers, families, and groups attending major events like the Ryder Cup 2027. Overlooking the 18th green of the Lahinch Old Course, this home boasts exceptional sea and golf course views and is just over one hour drive or a short helicopter ride from Adare Manor.",
    specs: [
      { label: "Bedrooms", value: "4 bedrooms; 3 King, One quadruple." },
      { label: "Bathrooms", value: "3 bathrooms" },
      { label: "Occupancy", value: "10" },
      { label: "Distance from Adare Manor course", value: "53 miles (1hr 10 mins drive)" },
      { label: "Distance to Park and Ride", value: "48 miles (1 hr 4 mins drive)" },
      { label: "Number of TVs", value: "2" },
      { label: "Square footage", value: "1,800 sq ft" },
      { label: "Dining seating", value: "8" },
      { label: "Kitchen seating", value: "4" },
    ],
    price: "POA",
    images: [
      "/images/houses/house 9/house-9-kitchen-3.webp",
      "/images/houses/house 9/house-9-kitchen-5.webp",
      "/images/houses/house 9/house-9-kitchen-living.webp",
      "/images/houses/house 9/house-9-living-room-1.webp",
      "/images/houses/house 9/house-9-living-room-2.webp",
      "/images/houses/house 9/house-9-living-room-4.webp",
      "/images/houses/house 9/house-9-kitchen-4.webp",
      "/images/houses/house 9/house-9-bathroom-2.webp",
      "/images/houses/house 9/house-9-bedroom-2.webp",
      "/images/houses/house 9/house-9-bedroom-3.webp",
      "/images/houses/house 9/house-9-bathroom-1.webp",
      "/images/houses/house 9/house-9-stairs.webp",
      "/images/houses/house 9/house-9-stairs-under.webp"
    ],
    thumbnail: "/images/houses/house 9/house-9-kitchen-3.webp",
    features: [
      "Open-plan kitchen, dining and living area with wood-burning stove",
      "Upstairs lounge with bar and panoramic golf and ocean views",
      "3 bedrooms with King beds, 1 bedroom with 4 single beds",
      "3 bathrooms with wet room rain showers",
      "Fully equipped utility room",
      "Architect-designed layout, ideal for social gatherings",
      "High-speed Wi-Fi, streaming services, and dedicated workspace",
      "Garage for golf clubs",
      "Outdoor BBQ and entertainment area",
      "Sauna, ice bath, and outdoor shower"
    ],
    amenities: [
      "A-rated energy-efficient home",
      "Short walk to Lahinch village, beach, and surf",
      "Hugo’s Bakery, cafés, restaurants, and traditional Irish pubs nearby",
      "5-minute drive to Cliffs of Moher",
      "Close to ferry for Aran Islands, The Burren, Loop Head, Doolin",
      "Lahinch Leisure Centre nearby",
      "Helicopter landing possible on Lahinch Golf Course (100m away)",
      "Welcome hamper provided on arrival",
      "Optional transport services (airport pick-up, transfers to Adare Manor)",
      "Laundry and catering available on request",
      "One-week rental only (week before, during, and after Ryder Cup available separately)",
      "Price on application"
    ],
    location: {
      lat: 52.9346,
      lng: -9.3432
    },
    walkingDistance: "Just over one hour drive to Adare Manor"
  },
  {
    id: "hillview-house",
    name: "Hillview House",
    subtitle:
      "Five-star modern residence for Ryder Cup 2027, up to 14 guests, approximately 45 minutes from Adare Manor; 20 minutes from Limerick Junction with direct trains to Adare.",
    bedrooms: 6,
    description:
      "Five-star modern residence for up to 14 guests, 45 minutes from Adare Manor, with train access to Adare via Limerick Junction.",
    fullDescription:
      "Hillview House is a beautifully finished, modern residence, offering an exceptional private retreat for groups attending the Ryder Cup 2027. Located just a 45-minute drive from Adare Manor and a 20-minute drive from Limerick Junction (with direct trains to Adare). This property combines contemporary design and generous living space.\n\nDesigned with both comfort and entertaining in mind, the home centres around a stunning open-plan kitchen, dining, and living area that flows seamlessly onto a private patio, ideal for relaxed evenings or hosting guests.\n\nThe property accommodates up to 12-14 guests sharing across six well-appointed double bedrooms, including a luxurious master suite complete with walk-in wardrobe. With four bathrooms and multiple spacious living areas, Hillview House delivers both privacy and flexibility.\n\nSet behind secure gates and positioned alongside a second residence, Hillview House also offers a unique opportunity for larger groups to secure both homes, creating an exclusive multi-residence solution in a private setting.\n\nThe property includes a modern kitchen, guest wifi, and private parking.",
    specs: [
      { label: "Bedrooms", value: "6 bedrooms; 2 doubles ensuite, 2 x 2 doubles with shared bathrooms." },
      { label: "Bathrooms", value: "4" },
      { label: "Occupancy", value: "12-14" },
      { label: "Distance from Adare Manor course", value: "26 miles (45 mins drive)" },
      { label: "Distance to Park and Ride", value: "23 miles (40 mins drive)" },
      { label: "Distance from Adare rail link", value: "12 miles (20 minutes drive + 30 min train approx)" },
      { label: "Number of TVs", value: "3" },
      { label: "Square footage", value: "4,300 sq ft" },
      { label: "Dining seating", value: "8-10" },
      { label: "Kitchen seating", value: "10" },
    ],
    price: "POA",
    images: [
      "/images/houses/house 13/house-13-exterior-4.webp",
      "/images/houses/house 13/house-13-exterior-1.webp",
      "/images/houses/house 13/house-13-kitchen-1.webp",
      "/images/houses/house 13/house-13-kitchen-2.webp",
      "/images/houses/house 13/house-13-sitting-1.webp",
      "/images/houses/house 13/house-13-sitting-2.webp",
      "/images/houses/house 13/house-13-bathroom-1.webp",
      "/images/houses/house 13/house-13-bathroom-2.webp",
      "/images/houses/house 13/house-13-master-1.webp",
      "/images/houses/house 13/house-13-master-2.webp",
      "/images/houses/house 13/house-13-master-3.webp",
      "/images/houses/house 13/house-13-bedroom-2-1.webp",
      "/images/houses/house 13/house-13-bedroom-2-2.webp",
      "/images/houses/house 13/house-13-bedroom-3-1.webp",
      "/images/houses/house 13/house-13-bedroom-4-1.webp",
      "/images/houses/house 13/house-13-bedroom-4-2.webp",
      "/images/houses/house 13/house-13-attic-1.webp",
      "/images/houses/house 13/house-13-attic-2.webp",
      "/images/houses/house 13/house-13-attic-3.webp",
      "/images/houses/house 13/house-13-kitchen-3.webp",
      "/images/houses/house 13/house-13-kitchen-4.webp",
      "/images/houses/house 13/house-13-exterior-38.webp",
      "/images/houses/house 13/house-13-exterior-25.webp",
      "/images/houses/house 13/house-13-exterior-31.webp",
      "/images/houses/house 13/house-13-exterior-34.webp",
    ],
    thumbnail: "/images/houses/house 13/house-13-exterior-4.webp",
    features: [
      "Six spacious double bedrooms",
      "Master en-suite with walk-in wardrobe",
      "Four modern bathrooms",
      "Open-plan kitchen, dining, and living space",
      "Direct access to private patio and outdoor area",
      "Secure electric gated entrance",
      "Contemporary five-star finish throughout",
      "Large, bright living areas designed for comfort and entertaining",
    ],
    amenities: [
      "Fully equipped modern kitchen with high-end appliances",
      "Stylish dining area suitable for group dining",
      "Comfortable lounge and relaxation spaces",
      "High-speed WiFi throughout",
      "Smart TVs and modern entertainment setup",
      "Quality bed linen and towels provided",
      "Laundry facilities",
      "Daily housekeeping",
      "Private parking within gated grounds",
      "Electric vehicle charging points",
      "Office space",
      "20 minutes from Limerick Junction, with direct trains to Adare",
    ],
    location: {
      lat: 52.3714932,
      lng: -8.3473484,
    },
    walkingDistance: "Approximately 45 minutes' drive to Adare Manor",
  },
  {
    id: "portland-house",
    name: "Portland House",
    subtitle:
      "Generous private residence for Ryder Cup 2027, just 20 minutes from Limerick Junction with direct trains to Adare; pairs naturally with neighbouring Hillview House.",
    bedrooms: 6,
    description:
      "Private residence for up to 14 guests, 45 minutes from Adare Manor, with train access to Adare via Limerick Junction.",
    fullDescription:
      "Portland House is a large private residence suited to extended families or groups for the Ryder Cup 2027. It sits just 45 minutes drive from Adare Manor and 20 minutes from Limerick Junction, where direct trains run to Adare. It can be booked alongside neighbouring Hillview House for larger parties who want two houses side by side.\n\nDownstairs revolves around a large reception space: a welcoming kitchen area, formal and informal sitting rooms, a study, and a sun room. Sleeping quarters are arranged across ground, first, and second floors, including a ground-floor master suite, a first-floor master, and two further first-floor bedrooms. Flexible attic accommodation with its own bathroom gives privacy and flexibility for mixed groups.\n\nAdditional touches include multiple bathrooms, an outdoor bar for relaxed evenings, and parking on site. The layout is designed for comfortable stays, with space to gather, work, and unwind between tournament days.",
    specs: [
      { label: "Bedrooms", value: "6 bedrooms; 3 doubles ensuite, 2 x 2 doubles with shared bathrooms, 1 double own bathroom" },
      { label: "Bathrooms", value: "7 and 1 half bathroom" },
      { label: "Occupancy", value: "12-14" },
      { label: "Distance from Adare Manor course", value: "26 miles (45 mins drive)" },
      { label: "Distance to Park and Ride", value: "23 miles (40 mins drive)" },
      { label: "Distance from Adare rail link", value: "12 miles (20 minutes drive + 30 min train approx)" },
      { label: "Number of TVs", value: "5" },
      { label: "Square footage", value: "6,000 sq ft" },
      { label: "Dining seating", value: "8-10" },
      { label: "Kitchen seating", value: "10" },
    ],
    price: "POA",
    images: [
      "/images/houses/house 14/house-14-exterior-21.webp",
      "/images/houses/house 14/house-14-kitchen-1.webp",
      "/images/houses/house 14/house-14-kitchen-2.webp",
      "/images/houses/house 14/house-14-sitting-1.webp",
      "/images/houses/house 14/house-14-sitting-2.webp",
      "/images/houses/house 14/house-14-sunroom-1.webp",
      "/images/houses/house 14/house-14-sunroom-2.webp",
      "/images/houses/house 14/house-14-sunroom-3.webp",
      "/images/houses/house 14/house-14-study-1.webp",
      "/images/houses/house 14/house-14-hall-1.webp",
      "/images/houses/house 14/house-14-master-ground-1.webp",
      "/images/houses/house 14/house-14-master-ground-2.webp",
      "/images/houses/house 14/house-14-master-ground-3.webp",
      "/images/houses/house 14/house-14-master-ground-4.webp",
      "/images/houses/house 14/house-14-master-ground-5.webp",
      "/images/houses/house 14/house-14-master-first-1.webp",
      "/images/houses/house 14/house-14-master-first-2.webp",
      "/images/houses/house 14/house-14-master-first-3.webp",
      "/images/houses/house 14/house-14-master-first-4.webp",
      "/images/houses/house 14/house-14-bedroom-2-1.webp",
      "/images/houses/house 14/house-14-bedroom-2-2.webp",
      "/images/houses/house 14/house-14-bedroom-2-3.webp",
      "/images/houses/house 14/house-14-bedroom-2-4.webp",
      "/images/houses/house 14/house-14-bedroom-3-1.webp",
      "/images/houses/house 14/house-14-bedroom-3-2.webp",
      "/images/houses/house 14/house-14-attic-1.webp",
      "/images/houses/house 14/house-14-attic-2.webp",
      "/images/houses/house 14/house-14-attic-3.webp",
      "/images/houses/house 14/house-14-bar-1.webp",
      "/images/houses/house 14/house-14-hall-2.webp",
      "/images/houses/house 14/house-14-bathroom-first-1.webp",
      "/images/houses/house 14/house-14-bathroom-first-2.webp",
      "/images/houses/house 14/house-14-exterior-13.webp",
      "/images/houses/house 14/house-14-exterior-35.webp",
    ],
    thumbnail: "/images/houses/house 14/house-14-exterior-21.webp",
    features: [
      "Multiple reception rooms plus a bright sun room",
      "Ground-floor and first-floor master bedroom suites",
      "Two further first-floor bedrooms plus flexible attic bedrooms and bathroom",
      "Outdoor bar area",
      "Study and generous back hall / circulation space",
      "Kitchen and informal dining geared for group stays",
      "Private parking on site",
    ],
    amenities: [
      "Fully equipped kitchen",
      "Comfortable lounging and dining areas",
      "High-speed Wi-Fi throughout",
      "Quality bed linen and towels provided",
      "Laundry facilities",
      "Multiple bathrooms across floors",
      "Private parking",
      "20 minutes from Limerick Junction, with direct trains to Adare",
    ],
    location: {
      lat: 52.3714932,
      lng: -8.3473484,
    },
    walkingDistance: "Approximately 45 minutes' drive to Adare Manor",
    videoUrl: "/videos/portlandhouse.mp4",
  },
  {
    id: "nead-fainleog",
    name: "Nead Fainleog",
    subtitle:
      "Five-bedroom executive residence two minutes from Adare Manor, with jacuzzi bath, steam room and countryside privacy for Ryder Cup 2027.",
    bedrooms: 5,
    description:
      "Five-bedroom executive country residence two minutes from Adare Manor, with jacuzzi bath, steam room and refined interiors.",
    fullDescription:
      "Nead Fainleog, meaning 'Swallow's Nest,' is an exceptional five-bedroom luxury residence that combines the warmth of Irish country living with the comforts of modern executive accommodation. Ideally located just a two-minute drive or a leisurely twenty-minute walk from the entrance to Adare Manor, the property offers the perfect balance of accessibility, privacy and space for Ryder Cup 2027.\n\nDesigned for both relaxation and entertaining, the heart of the home is a magnificent open-plan kitchen and dining space featuring a substantial central island, premium appliances and direct access to the outdoor entertaining area. Two beautifully appointed reception rooms provide elegant spaces for both formal entertaining and relaxed evenings, while five generously proportioned bedrooms, including three luxurious ensuites, ensure exceptional comfort for every guest.\n\nThe home also comes complete with a jacuzzi bath and private steam room, allowing guests to unwind after an unforgettable day at the Ryder Cup. Combining generous living accommodation, refined interiors and an enviable location close to the championship venue, Nead Fainleog provides an outstanding executive residence for families, corporate groups and discerning Ryder Cup guests.",
    specs: [
      { label: "Bedrooms", value: "5 bedrooms; 3 ensuite, 2 with adjoining bathroom" },
      { label: "Bathrooms", value: "6 including jacuzzi bath and steam room" },
      { label: "Occupancy", value: "10 guests maximum" },
      { label: "Reception rooms", value: "2" },
      { label: "Distance from Adare Manor course", value: "2-minute drive or 20-minute walk to Adare Manor entrance" },
      { label: "Number of TVs", value: "3" },
      { label: "Square footage", value: "3,900 sq ft" },
      { label: "Dining seating", value: "8" },
      { label: "Kitchen seating", value: "6" },
    ],
    price: "POA",
    images: [
      "/images/houses/neadfainleog/neadfainleog-exterior-1.webp",
      "/images/houses/neadfainleog/neadfainleog-kitchen-dining-2.webp",
      "/images/houses/neadfainleog/neadfainleog-kitchen-dining-1.webp",
      "/images/houses/neadfainleog/neadfainleog-diningroom-1.webp",
      "/images/houses/neadfainleog/neadfainleog-livingroom-1.webp",
      "/images/houses/neadfainleog/neadfainleog-sittingroom-1.webp",
      "/images/houses/neadfainleog/neadfainleog-bathroom-1.webp",
      "/images/houses/neadfainleog/neadfainleog-stairs-1.webp",
      "/images/houses/neadfainleog/neadfainleog-masterbedroom-1.webp",
      "/images/houses/neadfainleog/neadfainleog-bedroom1-1.webp",
      "/images/houses/neadfainleog/neadfainleog-bedroom2-1.webp",
      "/images/houses/neadfainleog/neadfainleog-bedroom3-1.webp",
      "/images/houses/neadfainleog/neadfainleog-exterior-2.webp",
      "/images/houses/neadfainleog/neadfainleog-exterior-3.webp",
      "/images/houses/neadfainleog/neadfainleog-exterior-5.webp",
      "/images/houses/neadfainleog/neadfainleog-exterior-7.webp",
    ],
    thumbnail: "/images/houses/neadfainleog/neadfainleog-exterior-1.webp",
    features: [
      "Five-bedroom executive country residence finished to an exceptional standard",
      "Three spacious en suite bedrooms with luxury furnishings, two spacious bedrooms with luxury furnishings and adjoining bathrooms",
      "Jacuzzi bath and private steam room",
      "Two elegant reception rooms for entertaining and relaxation",
      "Contemporary open-plan kitchen with oversized central island",
      "Premium American-style fridge freezer and high-specification appliances",
      "Walk-in pantry and fully equipped utility room",
      "Formal dining area",
      "Landscaped gardens with covered heated gazebo and BBQ area",
      "Beautiful timber flooring throughout",
      "Mature countryside setting offering privacy and tranquillity",
    ],
    amenities: [
      "Daily housekeeping",
      "High-speed WiFi throughout",
      "Three Smart TVs",
      "Outdoor gazebo and BBQ area",
      "Secure private parking",
      "Underfloor heating",
      "Open fireplace and kitchen stove",
      "Solar PV and EV charging",
      "Monitored security alarm",
    ],
    location: {
      lat: 52.55127116942097,
      lng: -8.79875286124995,
    },
    walkingDistance:
      "Two-minute drive or approximately twenty-minute walk to the entrance of Adare Manor and the Ryder Cup venue.",
    eircode: "V94 W959",
    matterportUrl: "https://my.matterport.com/show/?m=Byumeyi5wmc",
  },
  {
    id: "the-manor-lodge",
    name: "The Manor Lodge",
    subtitle:
      "Executive contemporary residence in Adare village, approximately 550 yards from the gates of Adare Manor.",
    bedrooms: 5,
    description:
      "Contemporary residence in picturesque Adare, just 550 yards from Adare Manor, offering refined private accommodation for Ryder Cup 2027.",
    fullDescription:
      "Positioned in the picturesque village of Adare, just 550 yards from the entrance to Adare Manor, The Manor Lodge is an exceptional contemporary executive residence offering one of the finest private accommodation experiences available for Ryder Cup 2027.\n\nExtending to approximately 4,000 square feet, the home combines contemporary architecture with elegant, light-filled interiors and beautifully landscaped gardens. Generous glazing and spacious open-plan living areas create a seamless connection between the home and its outdoor entertaining spaces, delivering understated luxury throughout.\n\nGuests are welcomed through a striking reception hall that also serves as an elegant formal dining space, creating a memorable first impression and an impressive setting for private dining and executive entertaining.\n\nAt the heart of the residence is a magnificent open-plan kitchen with an electric Aga, handcrafted island, walk-in pantry and informal dining area. A formal drawing room, separate TV lounge and exceptional outdoor entertaining pavilion with bespoke bar and Kamado Joe BBQ provide a variety of spaces for relaxation and hosting.\n\nThe residence comfortably accommodates up to ten guests across four luxurious double bedrooms and a flexible fifth bedroom. Two bedrooms are en-suite, while the principal suite features a spacious walk-in dressing room and a luxurious bathroom.\n\nWithin easy walking distance of Adare Manor and the award-winning restaurants, cafés and boutiques of Adare Village, The Manor Lodge is a flagship property within The Adare Collection Executive Portfolio.",
    specs: [
      { label: "Bedrooms", value: "5 double rooms, 2 ensuite, 2 with a shared bathroom" },
      { label: "Bathrooms", value: "3 + 1 half bathroom" },
      { label: "Occupancy", value: "8-10 max." },
      { label: "Distance from Adare Manor course", value: "550 yards." },
      { label: "Number of TVs", value: "2 smart TVs" },
      { label: "Square footage", value: "4,000 sqft" },
      { label: "Dining seating", value: "8-10" },
      { label: "Kitchen seating", value: "4" },
    ],
    price: "POA",
    images: [
      "/images/houses/house 15/house-15-exterior-1.webp",
      "/images/houses/house 15/house-15-exterior-2.webp",
      "/images/houses/house 15/house-15-entrance-1.webp",
      "/images/houses/house 15/house-15-entrance-2.webp",
      "/images/houses/house 15/house-15-entrance-3.webp",
      "/images/houses/house 15/house-15-entrance-4.webp",
      "/images/houses/house 15/house-15-kitchen-1.webp",
      "/images/houses/house 15/house-15-kitchen-2.webp",
      "/images/houses/house 15/house-15-kitchen-3.webp",
      "/images/houses/house 15/house-15-kitchen-4.webp",
      "/images/houses/house 15/house-15-kitchen-5.webp",
      "/images/houses/house 15/house-15-kitchen-6.webp",
      "/images/houses/house 15/house-15-living-1.webp",
      "/images/houses/house 15/house-15-living-2.webp",
      "/images/houses/house 15/house-15-living-3.webp",
      "/images/houses/house 15/house-15-sitting-1.webp",
      "/images/houses/house 15/house-15-sitting-2.webp",
      "/images/houses/house 15/house-15-bathroom-downstairs-1.webp",
      "/images/houses/house 15/house-15-stairs-1.webp",
      "/images/houses/house 15/house-15-stairs-2.webp",
      "/images/houses/house 15/house-15-stairs-3.webp",
      "/images/houses/house 15/house-15-bedroom-1-1.webp",
      "/images/houses/house 15/house-15-bedroom-1-2.webp",
      "/images/houses/house 15/house-15-bedroom-1-3.webp",
      "/images/houses/house 15/house-15-bedroom-1-4.webp",
      "/images/houses/house 15/house-15-bedroom-1-5.webp",
      "/images/houses/house 15/house-15-bedroom-1-6.webp",
      "/images/houses/house 15/house-15-bedroom-1-7.webp",
      "/images/houses/house 15/house-15-bedroom-2-1.webp",
      "/images/houses/house 15/house-15-bedroom-2-2.webp",
      "/images/houses/house 15/house-15-bathroom-upstairs-1.webp",
      "/images/houses/house 15/house-15-bedroom-3-1.webp",
      "/images/houses/house 15/house-15-bedroom-3-2.webp",
      "/images/houses/house 15/house-15-bedroom-4-1.webp",
      "/images/houses/house 15/house-15-bedroom-4-2.webp",
      "/images/houses/house 15/house-15-exterior-3.webp",
      "/images/houses/house 15/house-15-exterior-4.webp",
      "/images/houses/house 15/house-15-exterior-5.webp",
      "/images/houses/house 15/house-15-exterior-6.webp",
      "/images/houses/house 15/house-15-exterior-7.webp",
      "/images/houses/house 15/house-15-exterior-8.webp",
      "/images/houses/house 15/house-15-exterior-9.webp",
      "/images/houses/house 15/house-15-exterior-10.webp",
      "/images/houses/house 15/house-15-exterior-11.webp",
      "/images/houses/house 15/house-15-exterior-12.webp",
      "/images/houses/house 15/house-15-exterior-13.webp",
      "/images/houses/house 15/house-15-exterior-14.webp",
      "/images/houses/house 15/house-15-exterior-15.webp",
      "/images/houses/house 15/house-15-exterior-16.webp",
      "/images/houses/house 15/house-15-exterior-17.webp",
      "/images/houses/house 15/house-15-exterior-18.webp",
      "/images/houses/house 15/house-15-exterior-19.webp",
      "/images/houses/house 15/house-15-exterior-20.webp",
      "/images/houses/house 15/house-15-exterior-21.webp",
      "/images/houses/house 15/house-15-exterior-22.webp",
      "/images/houses/house 15/house-15-exterior-23.webp",
      "/images/houses/house 15/house-15-exterior-24.webp",
    ],
    thumbnail: "/images/houses/house 15/house-15-exterior-1.webp",
    features: [
      "Grand reception hall incorporating a formal dining space",
      "Beautifully appointed modern kitchen",
      "Handcrafted island with breakfast bar",
      "Electric Aga",
      "Walk-in pantry",
      "Outdoor bar with Kamado Joe BBQ for al fresco entertaining",
      "Lounge room, TV room and kitchen all leading out to patio",
      "Jacuzzi bath",
      "Wine fridge",
      "Secure gated private parking",
    ],
    amenities: [
      "High-speed WiFi and satellite TV",
      "Daily housekeeping",
      "BBQ",
      "Secure gated private parking",
    ],
    location: {
      lat: 52.5654,
      lng: -8.7845,
    },
    walkingDistance:
      "Approximately 550 yards from the gates of Adare Manor, within easy walking distance of Adare Village.",
    eircode: "V94 XNN0",
    videoUrl: "/videos/themanorlodge.mp4",
    availabilityStatus: "RESERVED",
  },
  {
    id: "derg-house",
    name: "Derg House",
    subtitle:
      "Exceptional luxury country residence, 20 minutes from Adare Manor and 11 minutes from the official Ryder Cup Park & Ride.",
    bedrooms: 5,
    bedroomsLabel: "4/5",
    description:
      "Over 8,500 sq ft of luxury accommodation in rolling countryside, 20 minutes from Adare Manor and 11 minutes from the Ryder Cup Park & Ride.",
    fullDescription:
      "Derg House is an exceptional luxury country residence offering over 8,500 square feet of beautifully appointed accommodation. Set amidst rolling countryside just 20 minutes from Adare Manor and only 11 minutes from the official Ryder Cup Park & Ride, this magnificent residence combines timeless elegance with contemporary luxury, creating a truly outstanding retreat for discerning guests.\n\nDesigned around spectacular open-plan living spaces and a striking double-height entrance hall, the property offers the perfect balance of grandeur and comfort. Expansive reception rooms, bespoke interiors, panoramic countryside views and exceptional natural light make Derg House an ideal residence for luxury stays. The bespoke kitchen opens seamlessly onto a spacious outdoor terrace and BBQ area, creating the perfect setting for alfresco dining and entertaining during the long September evenings.\n\nThe impressive master suite rivals those found in the world's finest hotels, while every room has been finished to an exceptional standard. Offering privacy, space and effortless luxury, Derg House provides a five-star residential experience in one of Ireland's most sought-after locations for Ryder Cup 27.",
    specs: [
      { label: "Bedrooms", value: "4 bedrooms + flexible fifth bedroom; 4 full ensuite bedrooms" },
      { label: "Bathrooms", value: "6" },
      { label: "Occupancy", value: "10 guests maximum" },
      { label: "Distance from Adare Manor course", value: "20 minutes from Adare Manor" },
      { label: "Distance to Park and Ride", value: "11 minutes to the official Ryder Cup Park & Ride" },
      { label: "Number of TVs", value: "3" },
      { label: "Square footage", value: "8,500+ sq ft" },
      { label: "Dining seating", value: "10" },
      { label: "Kitchen seating", value: "6" },
    ],
    price: "POA",
    images: [
      "/images/houses/derghouse/derghouse-main-exterior-1.webp",
      "/images/houses/derghouse/derghouse-kitchendining-1.webp",
      "/images/houses/derghouse/derghouse-kitchendining-2.webp",
      "/images/houses/derghouse/sitting-room-1.webp",
      "/images/houses/derghouse/siiting-room-2.webp",
      "/images/houses/derghouse/sitting-room-3.webp",
      "/images/houses/derghouse/derghouse-exterior-1.webp",
      "/images/houses/derghouse/derghouse-exterior-2.webp",
      "/images/houses/derghouse/derghouse-exterior-3.webp",
    ],
    thumbnail: "/images/houses/derghouse/derghouse-main-exterior-1.webp",
    features: [
      "Magnificent double-height entrance hall with sweeping staircase and gallery landing",
      "Grand reception room with bespoke cabinetry, grand piano and panoramic countryside views",
      "Exceptional open-plan family living space centred around a contemporary four-sided feature fireplace",
      "Luxury bespoke kitchen with oversized island, premium appliances and extensive preparation space",
      "Bespoke kitchen with direct access to a spacious outdoor terrace and BBQ area, perfect for alfresco dining and entertaining",
      "Elegant formal dining area overlooking the gardens",
      "Beautiful secondary sitting room, ideal for relaxation or private meetings",
      "Luxurious master suite with feature fireplace, walk-in dressing room and ensuite with jacuzzi bath",
      "Walk-in wardrobes in three of the bedrooms, offering generous storage and dressing space",
      "Dedicated home office with panoramic countryside views",
      "Large gallery landing overlooking the entrance hall",
    ],
    amenities: [
      "Daily housekeeping",
      "High-speed WiFi",
      "Luxury coffee station",
      "Large central kitchen island",
      "Spacious open-plan entertaining areas",
      "Landscaped gardens",
      "Outdoor terrace",
      "Secure private parking",
      "Panoramic countryside views",
      "Peaceful and private setting",
    ],
    location: {
      lat: 52.562213,
      lng: -8.781279,
    },
    walkingDistance:
      "Approximately 20 minutes' drive to Adare Manor; 11 minutes to the official Ryder Cup Park & Ride.",
  },
  {
    id: "riverston-abbey",
    name: "Riverston Abbey",
    subtitle:
      "Fifteen-bedroom executive estate in Nenagh with formal dining for 30, walled gardens and secure gated privacy for Ryder Cup 2027.",
    bedrooms: 15,
    description:
      "Distinguished private country residence in Nenagh with fifteen bedrooms, formal dining for thirty guests and walled gardens, approximately 40 minutes from Adare Manor.",
    fullDescription:
      "Nestled in the heart of Nenagh, County Tipperary, Riverston Abbey enjoys a superb setting within one of Ireland's most historic market towns. Set behind secure gates and surrounded by beautifully maintained walled gardens, the estate offers exceptional privacy while remaining close to Nenagh's cafés, restaurants and local amenities. A hotel adjacent to the property provides additional convenience for larger groups, making Riverston Abbey an outstanding base for executive groups during tournament week 2027.\n\nRecently refurbished and meticulously restored to an exceptional luxury standard, Riverston Abbey is one of Ireland's most distinguished private country residences. Rich in heritage and architectural character, this magnificent estate seamlessly blends timeless elegance with contemporary comfort to create an unforgettable residence for tournament guests.\n\nBehind its impressive façade lies an extraordinary collection of grand reception rooms, lavish entertaining spaces and beautifully appointed accommodation. The magnificent formal dining room comfortably seats up to 30 guests, creating an exceptional setting for executive dinners, private celebrations and bespoke entertaining experiences.\n\nThroughout the residence, original fireplaces, intricate period detailing and exquisite furnishings reflect the property's remarkable heritage while offering every modern comfort.\n\nOffering fifteen beautifully appointed bedrooms, fourteen en-suite bathrooms, extensive reception rooms, a large private courtyard and beautifully maintained walled gardens, Riverston Abbey is perfectly suited to executive hosting, sponsors, corporate groups and multi-generational family gatherings. Located approximately 40 minutes by motorway from Adare Manor, it provides a luxurious and distinctive base for an unforgettable stay.",
    specs: [
      { label: "Bedrooms", value: "15" },
      {
        label: "Bathrooms",
        value: "14 en-suite, 1 family bathroom, 3 guest cloakrooms",
      },
      { label: "Occupancy", value: "15–30 guests" },
      { label: "Distance from Adare Manor course", value: "40 minutes" },
      { label: "Number of TVs", value: "2 Smart TVs" },
      { label: "Square footage", value: "8,900 sq ft" },
      { label: "Dining seating", value: "Up to 30 guests" },
      { label: "Kitchen seating", value: "12 guests" },
    ],
    price: "POA",
    images: [
      "/images/houses/riverstonabbey/riverstonabbey-exterior-1.webp",
      "/images/houses/riverstonabbey/riverstonabbey-kitchen-1.webp",
      "/images/houses/riverstonabbey/riverstonabbey-dining-1.webp",
      "/images/houses/riverstonabbey/riverstonabbey-livingroom-1.webp",
      "/images/houses/riverstonabbey/riverstonabbey-livingroom-2.webp",
      "/images/houses/riverstonabbey/riverstonabbey-bathroom-1.webp",
      "/images/houses/riverstonabbey/riverstonabbey-stairway-1.webp",
      "/images/houses/riverstonabbey/riverstonabbey-bedroom-1.webp",
      "/images/houses/riverstonabbey/riverstonabbey-bedroom-2.webp",
      "/images/houses/riverstonabbey/riverstonabbey-bedroom-3.webp",
      "/images/houses/riverstonabbey/riverstonabbey-bedroom-4.webp",
      "/images/houses/riverstonabbey/riverstonabbey-exterior-2.webp",
      "/images/houses/riverstonabbey/riverstonabbey-exterior-3.webp",
    ],
    thumbnail: "/images/houses/riverstonabbey/riverstonabbey-exterior-1.webp",
    features: [
      "Grand entrance hall with sweeping staircase",
      "Magnificent formal dining room seating up to 30 guests",
      "Multiple elegant reception rooms",
      "Extensive sitting and entertainment areas",
      "Electric Aga",
      "Wine store",
      "Wood-burning fireplaces",
      "Lavish furnishings throughout",
      "Large private enclosed courtyard",
      "Extensive walled gardens",
      "Secure gated private parking",
      "Hotel adjacent to the property",
      "Ideal for executive groups and private entertaining",
    ],
    amenities: [
      "Daily housekeeping",
      "Full breakfast",
      "High-speed Wi-Fi",
      "Satellite TV",
      "2 large Smart TVs",
      "Multiple reception rooms",
      "Formal dining room for up to 30 guests",
      "Electric Aga",
      "BBQ",
    ],
    location: {
      lat: 52.86609666666666,
      lng: -8.186406666666667,
    },
    walkingDistance:
      "Approximately 40 minutes by motorway to Adare Manor and the Ryder Cup venue. Nestled in Nenagh, County Tipperary, behind secure gates with beautifully maintained walled gardens.",
    eircode: "E45 CD92",
    videoUrl: "/videos/riverstonabbey.mp4",
  },
  {
    id: "kildimo-house",
    name: "Kildimo House",
    subtitle:
      "Five-bedroom countryside residence in Kildimo, a two-minute walk from the village and approximately 12 minutes to the official Adare Park & Ride facility.",
    bedrooms: 5,
    description:
      "Five-bedroom Kildimo residence with an open-plan kitchen/dining, two sitting rooms, and private grounds—ideal for families and mixed groups, sleeping up to ten guests.",
    fullDescription:
      "Kildimo House is an impressive five-bedroom residence offering generous accommodation, contemporary living spaces and a peaceful countryside setting within convenient reach of Adare. The property is also just a two-minute walk from Kildimo village.\n\nExtending to approximately 4,000 sq. ft., the house has been designed for both relaxation and entertaining. At its heart is a bright, open-plan kitchen and dining area featuring extensive workspace, a substantial central island with seating, premium integrated appliances, a wine fridge and an instant boiling-water tap. The adjoining dining area seats up to eight guests, while the surrounding windows and garden access allow natural light to flow throughout the space.\n\nTwo sitting rooms and a separate lounge provide guests with a choice of comfortable areas in which to relax, socialise or enjoy private downtime.\n\nFive well-appointed double bedrooms, each with its own ensuite bathroom, provide comfortable accommodation for up to ten guests. One bedroom is conveniently located on the ground floor, making the house particularly suitable for a mixed group of corporate guests, couples or families.\n\nSet within mature private grounds, Kildimo House combines space, privacy and accessibility. A dedicated children’s play area in the rear garden makes the property particularly well suited to families. It is approximately 12 minutes from the official Park & Ride facility serving Adare, making it an excellent base for guests visiting the area in September 2027.",
    specs: [
      { label: "Bedrooms", value: "5 double bedrooms, all ensuite" },
      { label: "Bathrooms", value: "5 ensuite bathrooms" },
      { label: "Occupancy", value: "10 guests maximum" },
      { label: "Number of TVs", value: "3" },
      { label: "Square footage", value: "4,000 sqft" },
      { label: "Dining seating", value: "Up to 8 guests" },
      { label: "Kitchen seating", value: "4" },
      { label: "Distance to Park and Ride", value: "Approximately 12 minutes" },
    ],
    price: "POA",
    images: [
      "/images/houses/kildimolodge/kildimolodge-mainexterior-1.webp",
      "/images/houses/kildimolodge/kildimolodge-exterior-2.webp",
      "/images/houses/kildimolodge/kildimolodge-kitchendining-1.webp",
      "/images/houses/kildimolodge/kildimolodge-kitchendining-2.webp",
      "/images/houses/kildimolodge/kildimolodge-kitchendining-3.webp",
      "/images/houses/kildimolodge/kildimolodge-bedroom-1.webp",
      "/images/houses/kildimolodge/kildimolodge-bedroom-2.webp",
      "/images/houses/kildimolodge/kildimolodge-bedroom-3.webp",
    ],
    thumbnail: "/images/houses/kildimolodge/kildimolodge-mainexterior-1.webp",
    features: [
      "Five ensuite bathrooms",
      "Maximum overnight occupancy of ten guests",
      "Ground-floor bedroom",
      "Approximately 4,000 sq. ft. of accommodation",
      "Bright open-plan kitchen and dining area",
      "Dining seating for up to eight guests",
      "Kitchen island seating for four",
      "Two sitting rooms and a separate lounge",
      "Mature private gardens",
      "Children’s play area in the rear garden",
      "Outdoor entertaining and cooking area",
      "Two-minute walk to Kildimo village",
      "Approximately 12 minutes from the official Adare Park & Ride facility",
    ],
    amenities: [
      "High-speed Wi-Fi throughout",
      "Three televisions",
      "CCTV security",
      "Fully equipped contemporary kitchen",
      "Premium integrated appliances",
      "Wine fridge",
      "Instant boiling-water tap",
      "Induction hob and steam oven",
      "Separate utility area",
      "Private on-site parking",
    ],
    location: {
      lat: 52.6117,
      lng: -8.80685,
    },
    walkingDistance:
      "Two-minute walk to Kildimo village; approximately 12 minutes to the official Adare Park & Ride facility.",
    eircode: "V94 VY8W",
  },
  {
    id: "coolbawn-quay",
    name: "Coolbawn Quay",
    subtitle:
      "Boutique lakeside resort and private Irish village on Lough Derg, approximately one hour from Adare Manor.",
    bedrooms: 60,
    description:
      "Exclusive-use boutique resort on Lough Derg with 47 mostly ensuite rooms across a private Irish village, wellness facilities and a marina—ideal for large Ryder Cup 2027 groups.",
    fullDescription:
      "Coolbawn Quay is a boutique lakeside resort and private village built in the style of an old-world Irish settlement on the eastern shores of Lough Derg in North Tipperary. Hip and intimate in character, it combines rustic-chic village cottages scattered along leafy lanes with spacious lakeshore properties overlooking the harbour.\n\nThe resort offers 47 rooms in total—the majority ensuite—across 14 houses and 13 separate rooms, making it one of the most distinctive large-capacity private bases available for Ryder Cup 2027. Guests enjoy panoramic water views, private inlets and rolling countryside in a tranquil lakeside setting removed from the everyday.\n\nWellness is central to the experience, with grass-roofed treatment cabins on the deck above the water, bespoke therapies, yoga, wild swimming, sauna facilities and marked nature trails. A private marina provides exclusive waterfront access, while the village clubhouse offers an intimate pub and destination restaurant serving locally sourced produce.\n\nLocated approximately one hour's drive from Adare Manor, Coolbawn Quay suits executive groups, sponsors and multi-house parties seeking privacy, atmosphere and generous on-site amenities within practical reach of the Ryder Cup venue.",
    specs: [
      { label: "Bedrooms", value: "47 rooms across 14 houses and 13 separate rooms" },
      { label: "Bathrooms", value: "Majority ensuite" },
      { label: "Occupancy", value: "Up to 60 guests" },
      { label: "Distance from Adare Manor course", value: "Approximately 1 hour by road" },
      { label: "Square footage", value: "Approximately 2,745 sq m internal accommodation" },
      { label: "Dining seating", value: "Up to 220 guests in the Lakeshore Pavilion (on request)" },
      { label: "Restaurant amenities", value: "Clubhouse restaurant and bar" },
    ],
    price: "POA",
    images: [
      "/images/houses/coolbawnquay/coolbawnquay-exterior-1.webp",
      "/images/houses/coolbawnquay/coolbawnquay-exterior-2.webp",
      "/images/houses/coolbawnquay/coolbawnquay-exterior-3.webp",
      "/images/houses/coolbawnquay/coolbawnquay-interior-1.webp",
      "/images/houses/coolbawnquay/coolbawnquay-interior-2.webp",
      "/images/houses/coolbawnquay/coolbawnquay-interior-3.webp",
      "/images/houses/coolbawnquay/coolbawnquay-interior-4.webp",
      "/images/houses/coolbawnquay/coolbawnquay-landscape-1.webp",
      "/images/houses/coolbawnquay/coolbawnquay-exterior-4.webp",
      "/images/houses/coolbawnquay/coolbawnquay-exterior-5.webp",
    ],
    thumbnail: "/images/houses/coolbawnquay/coolbawnquay-exterior-1.webp",
    features: [
      "Boutique lakeside resort styled as a private Irish village",
      "Approximately 60 rooms, the majority ensuite, across 14 village houses and 13 separate rooms",
      "Charming rustic-chic cottages along leafy lanes leading to the harbour",
      "Panoramic Lough Derg views and lakeshore properties",
      "Private marina with exclusive guest access",
      "Grass-roofed wellness treatment cabins above the water",
      "Village pub and destination restaurant serving local seasonal produce",
      "Yoga, wild swimming, sauna, forest bathing and marked nature trails",
      "Meeting rooms with natural light and lakeside views",
      "Lakeshore Pavilion and banquet spaces for large private dining on request",
      "Centrally located with M7 motorway access (exit 26)",
      "Approximately one hour's drive from Adare Manor",
    ],
    amenities: [
      "High-speed Wi-Fi throughout",
      "On-site clubhouse restaurant and bar",
      "Wellness and spa treatment facilities",
      "Private marina access",
      "Quality bed linen and towels provided",
      "Daily housekeeping",
      "Ample private parking",
      "Marked nature trails and outdoor pursuits",
    ],
    location: {
      lat: 53.010401300587425,
      lng: -8.272649289736252,
    },
    walkingDistance:
      "Approximately one hour's drive to Adare Manor and the Ryder Cup venue. Boutique lakeside resort on the eastern shores of Lough Derg, Coolbawn, North Tipperary.",
  },
  {
    id: "oak-leaf-house",
    name: "Oak Leaf House",
    subtitle:
      "Deluxe residence approximately 12 minutes from Adare Manor, with secure gated parking and child-friendly countryside grounds.",
    bedrooms: 5,
    bedroomsLabel: "4/5",
    description:
      "Beautifully presented, child-friendly country residence of approximately 2,500 sq. ft., set behind secure electric gates with landscaped gardens and countryside views.",
    fullDescription:
      "The Oak Leaf is a beautifully presented, child-friendly country residence offering approximately 2,500 sq. ft. of spacious and comfortable accommodation. Set behind secure electric gates, this deluxe home combines contemporary interiors with welcoming living spaces, landscaped gardens and attractive countryside views.\n\nThe heart of the property is the bright open-plan kitchen and dining area. The beautifully appointed modern kitchen features a large granite-topped island, an American-style fridge-freezer and integrated appliances. The breakfast bar seats three guests, while the adjoining dining table can accommodate up to ten. Wide glazed doors fill the room with natural light and provide direct access to the rear patio and garden.\n\nGuests have a choice of two inviting living rooms. The main lounge includes generous seating, a large television and a traditional wood-burning stove, creating a cosy place to relax. A separate TV room features comfortable seating, bespoke fitted cabinetry, a large television and a contemporary electric fire.\n\nThe sleeping accommodation comprises four double bedrooms and one single bedroom. The master bedroom benefits from an en-suite bathroom and a walk-in wardrobe. The additional bedrooms are individually furnished and offer comfortable accommodation for families or groups.\n\nThere are three bathrooms in total. These include the master en suite, a stylish upstairs family bathroom with a freestanding bath and a separate downstairs bathroom with a walk-in rainfall shower.\n\nOutside, guests can enjoy a spacious patio with outdoor dining furniture and a BBQ, together with established gardens and open countryside views. The secure grounds and child-friendly setting make The Oak Leaf particularly well suited to families.\n\nThe property is also conveniently located just a one-minute drive or approximately seven-minute walk from Neville’s Bar & Restaurant, with the Croagh Park & Ride approximately seven minutes away by car.",
    specs: [
      { label: "Bedrooms", value: "Four double bedrooms and one single bedroom" },
      { label: "Bathrooms", value: "Three bathrooms, including one en suite" },
      { label: "Occupancy", value: "Up to 9 guests" },
      { label: "Distance from Adare Manor course", value: "Approximately 12 minutes’ drive" },
      { label: "Distance to Park and Ride", value: "Approximately seven minutes’ drive to Croagh Park & Ride" },
      { label: "Number of TVs", value: "3" },
      { label: "Square footage", value: "Approximately 2,500 sq. ft." },
      { label: "Dining seating", value: "Up to 10 guests" },
      { label: "Kitchen seating", value: "3" },
    ],
    price: "POA",
    images: [
      "/images/houses/oakleaf/oakleaf-exterior-1.webp",
      "/images/houses/oakleaf/oakleaf-kitchen-1.webp",
      "/images/houses/oakleaf/oakleaf-kitchendining-1.webp",
      "/images/houses/oakleaf/oakleaf-sittingroom-1.webp",
      "/images/houses/oakleaf/oakleaf-sittingroom-2.webp",
      "/images/houses/oakleaf/oakleaf-stairs-1.webp",
      "/images/houses/oakleaf/oakleaf-bedroom-1.webp",
      "/images/houses/oakleaf/oakleaf-bedroom-2.webp",
      "/images/houses/oakleaf/oakleaf-bedroom-3.webp",
      "/images/houses/oakleaf/oakleaf-upstairsbathroom-1.webp",
      "/images/houses/oakleaf/oakleaf-bathroom-1.webp",
      "/images/houses/oakleaf/oakleaf-exterior-2.webp",
    ],
    thumbnail: "/images/houses/oakleaf/oakleaf-exterior-1.webp",
    features: [
      "Beautifully appointed modern kitchen",
      "Large granite-topped kitchen island",
      "Breakfast bar seating for three",
      "Dining table seating for up to ten",
      "American-style fridge-freezer and integrated appliances",
      "Four double bedrooms and one single bedroom",
      "Master bedroom with en-suite bathroom and walk-in wardrobe",
      "Stylish family bathroom with freestanding bath",
      "Downstairs bathroom with walk-in rainfall shower",
      "Two comfortable living rooms",
      "Wood-burning stove and contemporary electric fire",
      "Three televisions",
      "Bright interiors with extensive natural light",
      "Direct access from the kitchen and dining area to the patio",
      "Landscaped garden with countryside views",
      "Child-friendly accommodation",
      "Secure electric gates and private gated parking",
    ],
    amenities: [
      "High-speed Wi-Fi",
      "Satellite television",
      "Fresh towels and bed linen",
      "Daily housekeeping",
      "BBQ and outdoor dining furniture",
      "Furnished rear patio",
      "Landscaped garden",
      "Secure private parking",
      "Modern cooking and kitchen facilities",
      "Family-friendly accommodation",
    ],
    location: {
      lat: 52.5245425,
      lng: -8.8187712,
    },
    walkingDistance:
      "Approximately 12 minutes’ drive to Adare Manor; one-minute drive or seven-minute walk to Neville’s Bar & Restaurant; approximately seven minutes to Croagh Park & Ride.",
  },
];
